/*
 * APX Autopilot project <http://docs.uavos.com>
 *
 * Copyright (c) 2003-2020, Aliaksei Stratsilatau <sa@uavos.com>
 * All rights reserved
 *
 * This file is part of APX Ground Control.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
#include "NodesSession.h"
#include "Database.h"

#include <App/AppDirs.h>

using namespace db::nodes;

Session::Session(QObject *parent, QString sessionName)
    : DatabaseSession(parent, "nodes", sessionName, {}, AppDirs::storage())
{
    new db::MakeTable(this,
                      "Node",
                      {
                          "key INTEGER PRIMARY KEY NOT NULL",
                          "uid TEXT NOT NULL UNIQUE",
                          "time INTEGER",  //time seen
                          "name TEXT",     //latest
                          "hardware TEXT", //latest
                          "version TEXT",  //latest
                      });
    new db::MakeIndex(this, "Node", "uid", true);
    new db::MakeIndex(this, "Node", "time", false);

    //Node dictionary
    new db::MakeTable(this,
                      "NodeDict",
                      {
                          "key INTEGER PRIMARY KEY NOT NULL",
                          "nodeID INTEGER NOT NULL",
                          "hash TEXT",              //content hash of all fields
                          "time INTEGER DEFAULT 0", //seen and synced
                          "name TEXT",              //node name
                          "hardware TEXT",
                          "version TEXT",
                          "cache TEXT", //cache hash generated by mcu
                          "FOREIGN KEY(nodeID) REFERENCES Node(key) ON DELETE CASCADE",
                      });
    new db::MakeIndex(this, "NodeDict", "nodeID", false);
    new db::MakeIndex(this, "NodeDict", "time", false);
    new db::MakeIndex(this, "NodeDict", "hash", false);
    new db::MakeIndex(this, "NodeDict", "cache", false);
    new db::MakeIndex(this, "NodeDict", "nodeID,hash", true);

    new db::MakeTable(this,
                      "NodeField",
                      {
                          // all field params together are unique
                          "key INTEGER PRIMARY KEY NOT NULL",
                          "name TEXT NOT NULL", //unique name, i.e. 'imu.ins.gyro'
                          "title TEXT",         //human readable title
                          "units TEXT",         //units of measure
                          "type TEXT NOT NULL", //group,byte,real,etc
                          "array INTEGER",
                      });
    new db::MakeIndex(this, "NodeField", "name,title,units,type,array", true);

    new db::MakeTable(this,
                      "NodeDictStruct",
                      {
                          "key INTEGER PRIMARY KEY NOT NULL",
                          "dictID INTEGER NOT NULL",
                          "fieldID INTEGER NOT NULL",
                          "fieldIndex INTEGER", //field order in dict
                          "FOREIGN KEY(dictID) REFERENCES NodeDict(key) ON DELETE CASCADE",
                          "FOREIGN KEY(fieldID) REFERENCES NodeField(key)",
                      });
    new db::MakeIndex(this, "NodeDictStruct", "dictID", false);
    new db::MakeIndex(this, "NodeDictStruct", "fieldID", false);
    new db::MakeIndex(this, "NodeDictStruct", "fieldIndex", false);

    new db::MakeTable(this,
                      "NodeFieldMeta",
                      {
                          // fields metadata cache
                          "key INTEGER PRIMARY KEY NOT NULL",
                          "name TEXT NOT NULL", // unique
                          "version INTEGER NOT NULL",
                          "meta TEXT NOT NULL",
                      });
    new db::MakeIndex(this, "NodeFieldMeta", "name", true);

    //Node parameters
    new db::MakeTable(this,
                      "NodeConf",
                      {
                          "key INTEGER PRIMARY KEY NOT NULL",
                          "dictID INTEGER NOT NULL",
                          "hash TEXT",    //sha1 of values
                          "time INTEGER", //seen time
                          "title TEXT",   //auto generated from labels
                          "FOREIGN KEY(dictID) REFERENCES NodeDict(key) ON DELETE CASCADE",
                      });
    new db::MakeIndex(this, "NodeConf", "dictID", false);
    new db::MakeIndex(this, "NodeConf", "hash", false);
    new db::MakeIndex(this, "NodeConf", "time", false);
    new db::MakeIndex(this, "NodeConf", "dictID,hash", true);

    new db::MakeTable(this,
                      "NodeConfValues",
                      {
                          "key INTEGER PRIMARY KEY NOT NULL",
                          "value TEXT",
                      });
    new db::MakeIndex(this, "NodeConfValues", "value", true);

    new db::MakeTable(this,
                      "NodeConfData",
                      {
                          "confID INTEGER NOT NULL",
                          "fieldID INTEGER NOT NULL",
                          "valueID INTEGER NOT NULL",
                          "subidx INTEGER",
                          "FOREIGN KEY(confID) REFERENCES NodeConf(key) ON DELETE CASCADE",
                          "FOREIGN KEY(fieldID) REFERENCES NodeDictStruct(key) ON DELETE CASCADE",
                          "FOREIGN KEY(valueID) REFERENCES NodeConfValues(key) ON DELETE CASCADE",
                      });
    new db::MakeIndex(this, "NodeConfData", "confID", false);
    new db::MakeIndex(this, "NodeConfData", "confID,fieldID,subidx", true);

    //Unit
    new db::MakeTable(this,
                      "Unit",
                      {
                          "key INTEGER PRIMARY KEY NOT NULL",
                          "uid TEXT",
                          "name TEXT",
                          "type TEXT",
                          "time INTEGER DEFAULT 0", //time seen
                      });
    new db::MakeIndex(this, "Unit", "uid,name,type", true);
    new db::MakeIndex(this, "Unit", "uid", false);
    new db::MakeIndex(this, "Unit", "name", false);
    new db::MakeIndex(this, "Unit", "type", false);
    new db::MakeIndex(this, "Unit", "time", false);

    //Unit nodes configs (commits)
    new db::MakeTable(this,
                      "UnitConf",
                      {
                          "key INTEGER PRIMARY KEY NOT NULL",
                          "hash TEXT NOT NULL UNIQUE", //sha1
                          "time INTEGER DEFAULT 0",    //time of snapshot
                          "title TEXT",                //auto generated
                          "unitID INTEGER NOT NULL",
                          "notes TEXT",
                          "FOREIGN KEY(unitID) REFERENCES Unit(key) ON DELETE CASCADE",
                      });
    new db::MakeIndex(this, "UnitConf", "hash", false);
    new db::MakeIndex(this, "UnitConf", "time", false);
    new db::MakeIndex(this, "UnitConf", "title", false);
    new db::MakeIndex(this, "UnitConf", "unitID", false);
    new db::MakeIndex(this, "UnitConf", "notes", false);
    new db::MakeIndex(this, "UnitConf", "hash,unitID", true);

    new db::MakeTable(this,
                      "UnitConfData",
                      {
                          //assigns nodes to unit
                          "unitConfID INTEGER NOT NULL",
                          "nodeConfID INTEGER NOT NULL",
                          "FOREIGN KEY(unitConfID) REFERENCES UnitConf(key) ON DELETE CASCADE",
                          "FOREIGN KEY(nodeConfID) REFERENCES NodeConf(key) ON DELETE CASCADE",
                      });
    new db::MakeIndex(this, "UnitConfData", "unitConfID", false);
    new db::MakeIndex(this, "UnitConfData", "nodeConfID", false);
    new db::MakeIndex(this, "UnitConfData", "unitConfID,nodeConfID", true);
}

Request::Request()
    : DatabaseRequest(Database::instance()->nodes)
{}

Request::Request(const QString &sql, const QVariantList &bind)
    : DatabaseRequest(Database::instance()->nodes, sql, bind)
{}
